import type { Product, Category, User, Order } from './types';

export const categories: Category[] = [
  { id: 'women', name: "Women's", imageId: 'category-women' },
  { id: 'men', name: "Men's", imageId: 'category-men' },
  { id: 'kids', name: "Kids'", imageId: 'category-kids' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Denim Jacket',
    description: 'A timeless denim jacket that is a must-have in every wardrobe. Made with high-quality, durable denim, this jacket offers a comfortable fit and a stylish look. Perfect for layering over any outfit.',
    price: 89.99,
    category: 'women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Black'],
    imageIds: ['product-1-a', 'product-1-b'],
    rating: 4.5,
    reviewCount: 120,
  },
  {
    id: '2',
    name: 'Essential Cotton T-Shirt',
    description: 'The perfect basic tee, crafted from 100% premium soft cotton. Features a classic crew neck and a modern, tailored fit. Available in multiple colors.',
    price: 24.99,
    category: 'men',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Gray', 'Navy'],
    imageIds: ['product-2-a'],
    rating: 4.8,
    reviewCount: 350,
  },
  {
    id: '3',
    name: 'Slim-Fit Black Jeans',
    description: 'Our best-selling slim-fit jeans in a versatile black wash. Designed with a hint of stretch for all-day comfort and a sleek silhouette.',
    price: 79.99,
    category: 'men',
    sizes: ['30', '32', '34', '36'],
    colors: ['Black'],
    imageIds: ['product-3-a'],
    rating: 4.6,
    reviewCount: 210,
  },
  {
    id: '4',
    name: 'Floral Print Summer Dress',
    description: 'A light and airy summer dress with a beautiful floral print. It features a flattering A-line cut and a comfortable, breathable fabric, making it ideal for warm weather.',
    price: 65.00,
    category: 'women',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Red', 'Blue'],
    imageIds: ['product-4-a'],
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: '5',
    name: 'Classic Trench Coat',
    description: 'An elegant and timeless trench coat in a versatile beige color. Perfect for transitional weather, it features a double-breasted front and a belted waist for a defined silhouette.',
    price: 149.99,
    category: 'women',
    sizes: ['S', 'M', 'L'],
    colors: ['Beige', 'Navy'],
    imageIds: ['product-5-a'],
    rating: 4.9,
    reviewCount: 150,
  },
  {
    id: '6',
    name: 'Cozy Fleece Hoodie',
    description: 'Stay warm and comfortable in our ultra-soft fleece hoodie. A perfect choice for a casual day out or a cozy night in. Features a kangaroo pocket and an adjustable drawstring hood.',
    price: 55.00,
    category: 'men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Gray', 'Black', 'Maroon'],
    imageIds: ['product-6-a'],
    rating: 4.8,
    reviewCount: 190,
  },
  {
    id: '7',
    name: 'Faux Leather Biker Jacket',
    description: 'Add an edge to your look with this classic biker jacket. Made from high-quality faux leather with authentic metal hardware. A true style statement.',
    price: 120.00,
    category: 'women',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black'],
    imageIds: ['product-7-a'],
    rating: 4.7,
    reviewCount: 95,
  },
  {
    id: '8',
    name: 'Modern Chino Pants',
    description: 'Versatile and stylish chino pants that can be dressed up or down. Made from comfortable stretch cotton for a perfect fit. A modern wardrobe essential.',
    price: 69.99,
    category: 'men',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Navy', 'Khaki', 'Gray'],
    imageIds: ['product-8-a'],
    rating: 4.5,
    reviewCount: 130,
  },
];

export const users: User[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', role: 'admin', createdAt: '2023-01-15' },
  { id: '2', name: 'Bob Smith', email: 'bob@example.com', role: 'customer', createdAt: '2023-02-20' },
  { id: '3', name: 'Charlie Brown', email: 'charlie@example.com', role: 'customer', createdAt: '2023-03-10' },
  { id: '4', name: 'Diana Prince', email: 'diana@example.com', role: 'customer', createdAt: '2023-04-05' },
];

export const orders: Order[] = [
  { id: 'ORD001', userId: '2', userName: 'Bob Smith', total: 114.98, status: 'Delivered', date: '2023-10-25', itemCount: 2 },
  { id: 'ORD002', userId: '3', userName: 'Charlie Brown', total: 65.00, status: 'Shipped', date: '2023-10-28', itemCount: 1 },
  { id: 'ORD003', userId: '4', userName: 'Diana Prince', total: 174.99, status: 'Pending', date: '2023-10-30', itemCount: 2 },
  { id: 'ORD004', userId: '2', userName: 'Bob Smith', total: 55.00, status: 'Cancelled', date: '2023-09-12', itemCount: 1 },
];
